/**
 * Provider-independent NFL Team identity and retained artwork.
 *
 * A provider alias may change without changing any value in this catalog.
 */
export const CANONICAL_NFL_TEAM_ABBREVIATIONS = [
  "ARI",
  "ATL",
  "BAL",
  "BUF",
  "CAR",
  "CHI",
  "CIN",
  "CLE",
  "DAL",
  "DEN",
  "DET",
  "GB",
  "HOU",
  "IND",
  "JAX",
  "KC",
  "LAC",
  "LAR",
  "LV",
  "MIA",
  "MIN",
  "NE",
  "NO",
  "NYG",
  "NYJ",
  "PHI",
  "PIT",
  "SEA",
  "SF",
  "TB",
  "TEN",
  "WAS",
] as const;

export type CanonicalNflTeamAbbreviation =
  (typeof CANONICAL_NFL_TEAM_ABBREVIATIONS)[number];

/** Immutable franchise identity. Values are never reordered or reused. */
export type NflTeamStableKey = `nfl-team:franchise-${number}`;

export type CanonicalNflTeam = Readonly<{
  stableKey: NflTeamStableKey;
  abbreviation: CanonicalNflTeamAbbreviation;
  name: string;
  logoUrl: string;
}>;

function team<const Abbreviation extends CanonicalNflTeamAbbreviation>(
  franchiseNumber: number,
  abbreviation: Abbreviation,
  name: string,
  logoUrl: string,
): Readonly<{
  abbreviation: Abbreviation;
  stableKey: NflTeamStableKey;
  name: string;
  logoUrl: string;
}> {
  const stableKey: NflTeamStableKey = `nfl-team:franchise-${franchiseNumber}`;
  return {
    stableKey,
    abbreviation,
    name,
    logoUrl,
  };
}

export const CANONICAL_NFL_TEAMS = {
  ARI: team(1,
    "ARI",
    "Arizona Cardinals",
    "https://r2.thesportsdb.com/images/media/team/badge/xvuwtw1420646838.png",
  ),
  ATL: team(2,
    "ATL",
    "Atlanta Falcons",
    "https://r2.thesportsdb.com/images/media/team/badge/rrpvpr1420658174.png",
  ),
  BAL: team(3,
    "BAL",
    "Baltimore Ravens",
    "https://r2.thesportsdb.com/images/media/team/badge/einz3p1546172463.png",
  ),
  BUF: team(4,
    "BUF",
    "Buffalo Bills",
    "https://r2.thesportsdb.com/images/media/team/badge/6pb37b1515849026.png",
  ),
  CAR: team(5,
    "CAR",
    "Carolina Panthers",
    "https://r2.thesportsdb.com/images/media/team/badge/xxyvvy1420940478.png",
  ),
  CHI: team(6,
    "CHI",
    "Chicago Bears",
    "https://r2.thesportsdb.com/images/media/team/badge/ji22531698678538.png",
  ),
  CIN: team(7,
    "CIN",
    "Cincinnati Bengals",
    "https://r2.thesportsdb.com/images/media/team/badge/qqtwwv1420941670.png",
  ),
  CLE: team(8,
    "CLE",
    "Cleveland Browns",
    "https://r2.thesportsdb.com/images/media/team/badge/squvxy1420942389.png",
  ),
  DAL: team(9,
    "DAL",
    "Dallas Cowboys",
    "https://r2.thesportsdb.com/images/media/team/badge/wrxssu1450018209.png",
  ),
  DEN: team(10,
    "DEN",
    "Denver Broncos",
    "https://r2.thesportsdb.com/images/media/team/badge/upsspx1421635647.png",
  ),
  DET: team(11,
    "DET",
    "Detroit Lions",
    "https://r2.thesportsdb.com/images/media/team/badge/lgsgkr1546168257.png",
  ),
  GB: team(12,
    "GB",
    "Green Bay Packers",
    "https://r2.thesportsdb.com/images/media/team/badge/rqpwtr1421434717.png",
  ),
  HOU: team(13,
    "HOU",
    "Houston Texans",
    "https://r2.thesportsdb.com/images/media/team/badge/wqyryy1421436627.png",
  ),
  IND: team(14,
    "IND",
    "Indianapolis Colts",
    "https://r2.thesportsdb.com/images/media/team/badge/wqqvpx1421434058.png",
  ),
  JAX: team(15,
    "JAX",
    "Jacksonville Jaguars",
    "https://r2.thesportsdb.com/images/media/team/badge/0mrsd41546427902.png",
  ),
  KC: team(16,
    "KC",
    "Kansas City Chiefs",
    "https://r2.thesportsdb.com/images/media/team/badge/936t161515847222.png",
  ),
  LAC: team(17,
    "LAC",
    "Los Angeles Chargers",
    "https://r2.thesportsdb.com/images/media/team/badge/vrqanp1687734910.png",
  ),
  LAR: team(18,
    "LAR",
    "Los Angeles Rams",
    "https://r2.thesportsdb.com/images/media/team/badge/8e8v4i1599764614.png",
  ),
  LV: team(19,
    "LV",
    "Las Vegas Raiders",
    "https://r2.thesportsdb.com/images/media/team/badge/xqusqy1421724291.png",
  ),
  MIA: team(20,
    "MIA",
    "Miami Dolphins",
    "https://r2.thesportsdb.com/images/media/team/badge/trtusv1421435081.png",
  ),
  MIN: team(21,
    "MIN",
    "Minnesota Vikings",
    "https://r2.thesportsdb.com/images/media/team/badge/qstqqr1421609163.png",
  ),
  NE: team(22,
    "NE",
    "New England Patriots",
    "https://r2.thesportsdb.com/images/media/team/badge/xtwxyt1421431860.png",
  ),
  NO: team(23,
    "NO",
    "New Orleans Saints",
    "https://r2.thesportsdb.com/images/media/team/badge/nd46c71537821337.png",
  ),
  NYG: team(24,
    "NYG",
    "New York Giants",
    "https://r2.thesportsdb.com/images/media/team/badge/vxppup1423669459.png",
  ),
  NYJ: team(25,
    "NYJ",
    "New York Jets",
    "https://r2.thesportsdb.com/images/media/team/badge/hz92od1607953467.png",
  ),
  PHI: team(26,
    "PHI",
    "Philadelphia Eagles",
    "https://r2.thesportsdb.com/images/media/team/badge/pnpybf1515852421.png",
  ),
  PIT: team(27,
    "PIT",
    "Pittsburgh Steelers",
    "https://r2.thesportsdb.com/images/media/team/badge/2975411515853129.png",
  ),
  SEA: team(28,
    "SEA",
    "Seattle Seahawks",
    "https://r2.thesportsdb.com/images/media/team/badge/wwuqyr1421434817.png",
  ),
  SF: team(29,
    "SF",
    "San Francisco 49ers",
    "https://r2.thesportsdb.com/images/media/team/badge/bqbtg61539537328.png",
  ),
  TB: team(30,
    "TB",
    "Tampa Bay Buccaneers",
    "https://r2.thesportsdb.com/images/media/team/badge/2dfpdl1537820969.png",
  ),
  TEN: team(31,
    "TEN",
    "Tennessee Titans",
    "https://r2.thesportsdb.com/images/media/team/badge/3td0f41779180767.png",
  ),
  WAS: team(32,
    "WAS",
    "Washington Commanders",
    "https://r2.thesportsdb.com/images/media/team/badge/rn0c7v1643826119.png",
  ),
} as const satisfies Record<CanonicalNflTeamAbbreviation, CanonicalNflTeam>;

export const CANONICAL_NFL_TEAM_LIST: readonly CanonicalNflTeam[] =
  CANONICAL_NFL_TEAM_ABBREVIATIONS.map(
    (abbreviation) => CANONICAL_NFL_TEAMS[abbreviation],
  );
